### ISSUE TITLE
Не рассчитывается качество

### ISSUE THREAD

**Issue by A-root** [Ku3mi41/OpenVirtaHelper#18]
Не рассчитывается качество продукции, выдает NaN. Так же не верно считает с/с
Например для "Кондитерских изделий - http://ovh.belyan.in/product/1497.html", "Автозапчастей - http://ovh.belyan.in/product/370077.html". 
Сдается мне из-за последних исправлений кода

**Comment by VDenisyuk** [comment]
Проблема в том, что на хостинге залиты не последние версии html-страниц предприятий и продуктов. Снйчас там старые ID у эелементов.

**Comment by Ku3mi41** [comment]
FTPloy не отработал. Залил вручную. Сейчас должно все работать.
