### ISSUE TITLE
Домен

### ISSUE THREAD

**Issue by agerov-vrt** [Ku3mi41/OpenVirtaHelper#20]
Приветствую. 
Добавь в настройках проекта домен **virtonomica.info** и напиши мне Ip для A-записи, пожалуйста. 
Пусть у калькулятора будет свой прямой домен, тем более virtonomica.info указана в официальной вики как калькулятор :)

**Comment by Ku3mi41** [comment]
https://help.github.com/articles/troubleshooting-custom-domains/
> # Multiple domains in CNAME file
> A CNAME file can contain only one domain. To point multiple domains to the same Page, set up redirects through your DNS provider.

Единственный возможный custom domain уже указан. Придется настраивать web-форвардинг.

**Comment by agerov-vrt** [comment]
Домен был мной куплен ещё в 2009, затем в 2015 перерегистрирован. Всё это время он был основным доменом для справки виртономики, начало которой положил DANU.Я рад, что справочник теперь в открытом виде, потому и хочу дать ему постоянный условно официальный домен. Если сделать форвардинг, то, безусловно перейдя по адресу virtonomica.info люди будут попадать в справочник, но основное зеркало останется прежним (кобр123.гитхаб.ио).CNAME сделать для домена 2-го уровня нельзя. Потому и вопрос к переназначению.  -- С уважением,Александр Геров+7921 938 0631   10.03.2018, 14:25, "Ku3mi41" <notifications@github.com>:https://help.github.com/articles/troubleshooting-custom-domains/Multiple domains in CNAME fileA CNAME file can contain only one domain. To point multiple domains to the same Page, set up redirects through your DNS provider.Единственный возможный custom domain уже указан. Придется настраивать web-форвардинг.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
